baseURL = "https://dynamics365blog.andaze.com"
languageCode = "en-us"
title = "My New Hugo Site"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  env = "devlop"  
  imageratio = "1"
  imagewidth = "700"
